### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by HCHCHH** [takaomag/docker.image.cassandra#1]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but they are set to be enabled by default:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them?
Thanks!

**Comment by takaomag** [comment]
Since I have not used Cassandra in about 1 year, I don't know current status. This docker image is Cassandra 3.11.2 though, latest version is 3.11.4..

The materialized view feature is very useful with some cost (write latency). I used this feature in my production environments and I have not met with any issues about it. If your data model requires it, I recommend this feature. If not, you can disable it. An example use case is [my stackoverflow answer](https://stackoverflow.com/questions/47159469/pyspark-cassandra-getting-distinct-values-of-partition-key/47185919#47185919).

Transient replication seems to be relatively new feature. I don't know it well.
http://cassandra.apache.org/blog/2018/12/03/introducing-transient-replication.html

Anyway, if you don't use a feature, you can disable it.
